INSERT INTO PRODUTO (ID, DESCRICAO, VALOR) VALUES(1, 'NOTEBOOK', 2800.90);
INSERT INTO PRODUTO (ID, DESCRICAO, VALOR)  VALUES(2, 'SMARTPHONE', 1258.00);
INSERT INTO PRODUTO (ID, DESCRICAO, VALOR) VALUES(3, 'RYZEN 7 2700X', 1600.99);

INSERT INTO ENDERECO (ID, CEP, LOGRADOURO, MUNICIPIO, UF) VALUES(1, '86706-678', 'CAMINHEIRO OCRE', 'ARAPONGAS', 'PR');
INSERT INTO ENDERECO (ID, CEP, LOGRADOURO, MUNICIPIO, UF) VALUES(2, '86015-300', 'MARTIN LUTHER KING', 'LONDRINA', 'PR');

INSERT INTO CLIENTE (ID, NOME, EMAIL, CPF, ENDERECO) VALUES(1, 'DENNER VINICIUS DE ALMEIDA', 'DENNERALMEIDA@EDU.UNIFIL.BR', '826.586.409-43', 1);
INSERT INTO CLIENTE (ID, NOME, EMAIL, CPF, ENDERECO) VALUES(2, 'TESTE DA API', 'TESTE@EDU.UNIFIL.BR', '765.869.889-00', 2);